# Generated by Django 3.2.6 on 2022-12-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='Post-Images/%Y-Year/%F-Month/'),
            preserve_default=False,
        ),
    ]
